#!/usr/bin/env bash
# Install nginx on your web-01

apt-get -y update
apt-get -y install nginx
# Adjust firewall
ufm allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
