#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt -y update
sudo apt -y install nginx
# Adjust firewall
sudo ufm allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
