#!/usr/bin/env bash
# script used to redirect to another page

# sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

echo "
	server {
		listen 80 default_server;
		listen [::]:80 default_server;
		
		# location /redirect_me {
		#	return 301  https://www.youtube.com/watch?v=QH2-TGUlwu4;
		# }

		rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanet;
	}
" | sudo tee /etc/nginx/sites-available/default

sudo systemctl reload nginx
