#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# (on web-01 and web-02)

url = "https://www.youtube.com/watch?v=QH2-TGUlwu4"

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

echo "server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;

		location /redirect_me {
			return 301 $url;
		}
	}
" | sudo tee /etc/nginx/sites-available/default

service nginx restart
