#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

sudo apt update
sudo apt install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt install haproxy=2.4.\*

# configuring
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

# copy the default configuration file to backup file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/original.cfg

echo "
frontend myfrontEnd
	bind *:80
	timeout client 40s
	default_backend mybackEnd

backend mybackEnd
	balance roundrobin
	timeout connect 10s
	timeout server 50s	
	server web-01 54.210.89.123:80 check
	server web-02 54.210.89.123:80 check
	" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy start
