#!/usr/bin/env bash

# Install and configure HAproxy on lb-01 server.

sudo apt update
sudo apt install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt install haproxy=2.4.\*


