#!/usr/bin/env bash
# display To infinity and beyond with 2s delay
# display I am invincible!!! when receiving a SIGTERM signal
# interrupted using ^C

trap "echo I am invincible!!!" SIGTERM 
while :; do
	echo "To infinity and beyond"
	sleep 2s	
done
