#!/usr/bin/env bash
# script that block all incoming traffics except some TCP ports

sudo apt-get update
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
