#!/usr/bin/env bash
# fix nginx config file permission and user

sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
